[project]
name = "vrs-matcher-example-plugin"
version = "0.1.0"
description = "An example custom matching algorithm plugin for vrs-matcher"
readme = "README.md"
authors = [
    { name = "Liam Beckman", email = "lbeckman314@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "vrs-matcher",
]

[project.entry-points."vrs_matcher.plugins"]
example = "vrs_matcher_example_plugin.example_plugin:create_plugin"

[dependency-groups]
dev = [
    "pytest>=8",
]

[build-system]
requires = ["uv_build>=0.11.9,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
vrs-matcher = { git = "https://github.com/EllrottLab/vrs-matcher.git" }
